[build-system]
requires = ["setuptools>=61.0", "versioningit~=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pylinks"
version = "0.0.0"
dependencies = [
]

[tool.setuptools.packages.find]
namespaces = false
